apiVersion: v1
kind: Service
metadata:
  name: wyn-svc
  namespace: wyn-enterprise
spec:
  type: NodePort
  ports:
  - port: 31980
    protocol: TCP
    name: wyn-svc-port
    nodePort: 31980
    targetPort: 51980
  selector:
    app: wyn
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wyn
  namespace: wyn-enterprise
spec:
  nodeSelector:
    node: node02
  selector:
    matchLabels:
      app: wyn
  serviceName: wyn-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: wyn
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: wyn-co
        image: grapecitycn/wyn-enterprise
        imagePullPolicy: Always
        ports:
        - containerPort: 51980
        volumeMounts:
        - name: wyn-pvc
          mountPath: /var/lib/postgresql/data
        - name: font-path
          mountPath: /usr/share/fonts/yahei
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
      volumes:
      - name: font-path
        hostPath:
          path: /usr/share/fonts/yahei
  volumeClaimTemplates:
  - metadata:
      name: wyn-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
      storageClassName: wyn-storage