#apiVersion: v1
#kind: Service
#metadata:
#  name: grafana
#  namespace: grafana
#  labels:
#    app: grafana
#    component: core
#spec:
#  type: NodePort
#  ports:
#    - port: 3000
#  selector:
#    app: grafana
#    component: core


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana
spec:
  type: NodePort
  ports:
#  - port: 80
  - port: 3000
    targetPort: 3000
    nodePort: 30007
  selector:
    app: grafana


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: grafana
spec:
  serviceName: "grafana"
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
              subPath: grafana
      securityContext:
        fsGroup: 472
        runAsUser: 472
  volumeClaimTemplates:
    - metadata:
        name: grafana-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: hadoop-storage
        resources:
          requests:
            storage: 1Gi
