apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: es
data:
  elasticsearch.yml: |
    cluster.name: "${NAMESPACE}"
    node.name: "${POD_NAME}"
    network.host: 0.0.0.0
    discovery.seed_hosts: "es-in" 
    cluster.initial_master_nodes: "es-0,es-1,es-2"