---
apiVersion: v1
kind: Service
metadata:
  name: es-in
  namespace: es
  labels:
    k8s-app: es
spec:
  selector:
    k8s-app: es
  clusterIP: None
  ports:
  - name: in
    port: 9300
    protocol: TCP
    
---
apiVersion: v1
kind: Service
metadata:
  name: es-out
  namespace: es
  labels:
    k8s-app: es
spec:
  selector:
    k8s-app: es
  type: NodePort  
  ports:
  - name: out
    port: 9200
    nodePort: 9200
    protocol: TCP    
    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  namespace: es
  labels:
    k8s-app: es
spec:
  replicas: 3
  serviceName: es
  selector:
    matchLabels:
      k8s-app: es
  template:
    metadata:
      labels:
        k8s-app: es
    spec:
      containers:
      - name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: '0.3'
            memory: 1Gi
        volumeMounts:
          - name: es-config
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
      volumes:
        - name: es-config
          configMap:
            name: es-config