---
apiVersion: v1
kind: Secret
metadata:
  name: hive-metastore-secret
  namespace: hive
  labels:
    app: hive
type: Opaque
data:
  database-dba-password: Y3NickBoaXZl
  database-user-password: Y3NickBoaXZl
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hive
  namespace: hive
spec:
  serviceName: "hive"
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
      labels:
        app: hive
    spec:
      containers:
        - name: hive
          image: bantianyinshi/hadoop:3.2.1
          imagePullPolicy: Always
          command: ["bash","-c"]
          args:
            - |
              set -ex
              /hadoop/bin/hadoop fs -mkdir -p /tmp
              /hadoop/bin/hadoop fs -mkdir -p /user/hive/warehouse
              /hadoop/bin/hadoop fs -chmod g+w /tmp
              /hadoop/bin/hadoop fs -chmod g+w /user/hive/warehouse
              /hive/bin/hiveserver2 &
              /hive/bin/hive --service metastore
          ports:
            - containerPort: 10000
            - containerPort: 10002
            - containerPort: 9083
          env:
            - name: HADOOP_CONF_DIR
              value: /hadoop/etc/hadoop
            - name: HIVE_METADATA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hive-metastore-secret
                  key: database-user-password
          volumeMounts:
            - name: hadoop-config-volume
              mountPath: /etc/hadoop
            - name: hive-custom-config-volume
              mountPath: /hive/conf
            - name: hive
              mountPath: /hive
      volumes:
        - name: hive-custom-config-volume
          configMap:
            name: hive-custom-config-cm
  volumeClaimTemplates:
    - metadata:
        name: hadoop-config-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: hadoop-storage
    - metadata:
        name: hive
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
        storageClassName: hadoop-storage
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: hive
  name: hive-service
  namespace: hive
spec:
  ports:
    - port: 10000
      targetPort: 10000
      name: thrift
    - port: 10002
      targetPort: 10002
      name: webui
    - port: 9083
      targetPort: 9083
      name: metastore
  selector:
    app: hive
  type: NodePort