apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-custom-config-cm
  namespace: hive
  labels:
    app: hive
data:
#  bootstrap.sh: |-
#    #!/bin/bash
#    set -x
#    cd /root/bootstrap
#
#    # Apply custom config file context
#    for cfg in ./*; do
#      if [[ ! "$cfg" =~ bootstrap.sh ]]; then
#        cat $cfg > $HIVE_HOME/conf/${cfg##*/}
#      fi
#    done
#
#    # Replace hive metadata password
#    sed -i 's/${HIVE_METADATA_PASSWORD}/'$HIVE_METADATA_PASSWORD'/g' `grep '${HIVE_METADATA_PASSWORD}' -rl $HIVE_HOME/conf`
#
#    # initSchema
#    if [[ ! -e $HADOOP_CONF_DIR/hive-metastore-initialization.out ]]; then
#      $HADOOP_HOME/bin/hadoop fs -mkdir -p /tmp
#      $HADOOP_HOME/bin/hadoop fs -mkdir -p /user/hive/warehouse
#      $HADOOP_HOME/bin/hadoop fs -chmod g+w /tmp
#      $HADOOP_HOME/bin/hadoop fs -chmod g+w /user/hive/warehouse
#
#      $HIVE_HOME/bin/schematool -dbType mysql -initSchema --verbose &> $HADOOP_CONF_DIR/hive-metastore-initialization.out
#    fi
#
#    $HIVE_HOME/bin/hiveserver2 &
#    $HIVE_HOME/bin/hive --service metastore &
#
#    cp $HIVE_HOME/conf/hive-env.sh.template $HIVE_HOME/conf/hive-env.sh && echo "export HADOOP_CLIENT_OPTS=\"-Xmx512m -XX:MaxPermSize=1024m \$HADOOP_CLIENT_OPTS\"" >> $HIVE_HOME/conf/hive-env.sh
#
#    # keep running
#    sleep infinity
  hive-site.xml: |-
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>hive</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>csbr@hive</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:mysql://192.168.5.200:3306/metastore?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false&amp;autoReconnect=true&amp;serverTimezone=Asia/Shanghai</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>com.mysql.cj.jdbc.Driver</value>
      </property>
      <property>
        <name>system:java.io.tmpdir</name>
        <value>/tmp</value>
      </property>
      <property>
        <name>system:user.name</name>
        <value>hive</value>
      </property>
      <property>
          <name>hive.metastore.schema.verification</name>
          <value>false</value>
      </property>
      <!-- 这是hiveserver2 -->
      <property>
          <name>hive.server2.thrift.port</name>
          <value>10000</value>
      </property>
      <property>
          <name>hive.server2.thrift.bind.host</name>
          <value>0.0.0.0</value>
      </property>
    </configuration>