---
apiVersion: v1
kind: Service
metadata:
  name: zeppelin-server
  namespace: zeppelin
  labels:
    app: zeppelin
spec:
  type: NodePort
  ports:
    - port: 18080
      name: zeppelin
      nodePort: 18080
  selector:
    app: zeppelin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeppelin
  namespace: zeppelin
  labels:
    name: zeppelin
spec:
  serviceName: "zeppelin"
  replicas: 1
  selector:
    matchLabels:
      app: zeppelin
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      containers:
      - name: zeppelin
        image: "apache/zeppelin:0.9.0"
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 18080
            protocol: TCP
        env:
          - name: ZEPPELIN_PORT
            value: "18080"
          - name: ZEPPELIN_K8S_CONTAINER_IMAGE
            value: apache/zeppelin:0.9.0
          - name: ZEPPELIN_RUN_MODE
            value: k8s